spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Tariq@123
  application:
    name: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
